### ISSUE TITLE
Use mozilla-runner to start firefox

### ISSUE THREAD

**Issue by erikvold** [mozilla-jetpack/jpm#206]
https://github.com/mozilla-b2g/mozilla-runner

**Comment by erikvold** [comment]
I made https://github.com/erikvold/fx-runner instead

**Comment by anaran** [comment]
@erikvold 
> I made https://github.com/erikvold/fx-runner instead
is a 404 now.

I also get

```
~/tmp/mozilla/jpm$ npm install
npm WARN package.json fx-runner@0.0.7 No repository field.
~/tmp/mozilla/jpm$
```

**Comment by chitcharonko** [comment]
I'm having the same problem here...

**Comment by msangel** [comment]
Up

**Comment by kumar303** [comment]
The repository has been deleted and I don't know of any mirrors so we'll need a new patch for this I guess.

**Comment by kumar303** [comment]
oh, my bad, the source had already moved to https://github.com/mozilla-jetpack/node-fx-runner

**Comment by kumar303** [comment]
looks like the repository field was already updated too: https://github.com/mozilla-jetpack/node-fx-runner/blob/master/package.json#L19

**Comment by kumar303** [comment]
I'll try to upgrade jpm's dep version here https://github.com/mozilla-jetpack/jpm/pull/438
