### ISSUE TITLE
/usr/bin/firefox not found

### ISSUE THREAD

**Issue by nschloe** [mozilla-jetpack/jpm#297]
I installed Firefox 38 (beta, for now) under
```
$ which firefox 
/usr/bin/firefox
```
yet _jpm_ can't find it:
```
$ jpm run
JPM undefined Starting jpm run on PaperHive
Creating XPI
JPM undefined XPI created at /tmp/@paperhive-firefox-addon-0.0.0.xpi (3344ms)
Created XPI at /tmp/@paperhive-firefox-addon-0.0.0.xpi
JPM undefined Creating a new profile
JPM undefined No Firefox binary found at null
JPM undefined Specify a Firefox binary to use with the `-b` flag.
JPM undefined Error: spawn /usr/lib64/firefox ENOENT
```
Explicitly providing the path does work
```
$ jpm run -b /usr/bin/firefox 
JPM undefined Starting jpm run on PaperHive
Creating XPI
JPM undefined XPI created at /tmp/@paperhive-firefox-addon-0.0.0.xpi (3530ms)
Created XPI at /tmp/@paperhive-firefox-addon-0.0.0.xpi
JPM undefined Creating a new profile
```
but really this shouldn't be necessary

**Comment by freaktechnik** [comment]
The problematic code is in fx-runner: https://github.com/erikvold/fx-runner/blob/master/lib/utils.js#L110-L118

I'm not sure, why it tries to launch firefox from the lib folder by default, since executables should always be linked to in bin... But best would probably be to launch it via /usr/bin/env, so it includes other paths aswell, but then again, some systems don't have /usr/bin/env.

**Comment by benmccann** [comment]
+1 i'm having the same problem

**Comment by benmccann** [comment]
@freaktechnik the fx-runner package you linked to is gone. do you know where that code is located now?

**Comment by freaktechnik** [comment]
It's still on npm, that's all I know: https://www.npmjs.com/package/fx-runner

**Comment by stripthis** [comment]
This looked interesting but was not merged :) https://github.com/mozilla/jpm/commit/9e379a04536fcf6bf5545833f444f692c666453f

**Comment by jsantell** [comment]
fx-runner has been reclaimed and moved to https://github.com/mozilla-jetpack/node-fx-runner

**Comment by benmccann** [comment]
Thanks for the pointer @jsantell. I refiled the bug there since it's really a bug in that project. https://github.com/mozilla-jetpack/node-fx-runner/issues/2

**Comment by jsantell** [comment]
@benmccann thanks!

**Comment by kumar303** [comment]
according to https://github.com/mozilla-jetpack/jpm/issues/453 it looks like `-b` is working as expected now.

**Comment by freaktechnik** [comment]
@kumar303 this is not about -b, this is about without -b.

**Comment by kumar303** [comment]
Ah, whoops. Yes, `-b` shouldn't be necessary for this case, since `which firefox` shows that it's on the path.

**Comment by BaNru** [comment]
> JPM [info] Creating a new profile
> JPM [error] No Firefox binary found at null
> JPM [error] Specify a Firefox binary to use with the `-b` flag.
> JPM [error] Error: spawn /usr/lib64/firefox ENOENT

The solution to this problem on Linux:
1. Create a folder if it is missing (as root): `mkdir /usr/lib64`
2. Create a link to FF: `ln -s $(which firefox) /usr/lib64/firefox`

Решение этой проблемы на Linux:
1. Создать папку, если она отсутствует (из под root): `mkdir /usr/lib64`
2. Создать ссылку на FF: `ln -s $(which firefox) /usr/lib64/firefox`

**Comment by rafaelcpalmeida** [comment]
@BaNru solution worked for me!

Linux Mint 17.3

**Comment by kumar303** [comment]
this should be fixed in https://github.com/mozilla-jetpack/jpm/releases/tag/1.1.3
