### ISSUE TITLE
Missing `global` object?

### ISSUE THREAD

**Issue by empyrical** [mozilla-jetpack/jpm#312]
I noticed while setting up a JPM extension that there doesn't seem to be a `global`, `window`, etc. variable present. I also tried using a few polyfills, and noticed that patched `Array`, `String`, etc. objects in one js module don't seem to have an effect on another. Is this by design, or did I set something up incorrectly?

Hacked up example of what I mean on the Polyfill thing:

index.js:

```js
Array.test = 'hello, world!';

require('./test')
```

test.js:

```js
console.log('exists?', Array.test);
```

Expected output:

    exists? hello, world!

Got:

    exists? undefined

Using jpm version `1.0.0`

**Comment by empyrical** [comment]
Found out the reason this is, and a work around that can be used for the time being:

https://gist.github.com/empyrical/f1cca44da1f81cb09a26

**Comment by jsantell** [comment]
This is the nature of the SDK environment; and it's intended, for what it's worth, but any changes for this should be filed as an [SDK bug](https://bugzilla.mozilla.org/enter_bug.cgi?product=Add-on%20SDK&component=General)

**Comment by empyrical** [comment]
Alright, thanks for the heads up!
