### ISSUE TITLE
jpm xpi needs option to specify the output

### ISSUE THREAD

**Issue by bgirard** [mozilla-jetpack/jpm#315]
Hit this while migrating from cfx and this is breaking my build script because now the output file now changes each version.

**Comment by lepolt** [comment]
+1, this breaks our build scripts (which try to be as dumb and generic as possible).

**Comment by Standard8** [comment]
@kumar303 I believe this is fixed now with commit 8059d86?

**Comment by kumar303** [comment]
Ah, yes it was. See https://github.com/mozilla-jetpack/jpm/pull/544 for discussion.
