### ISSUE TITLE
jpm linux error /usr/bin/env: node: No such file or directory AND Error: spawn ENOENT

### ISSUE THREAD

**Issue by FloydERoberts3** [mozilla-jetpack/jpm#321]
Thanks every one - I just wanted to post a quick solution to a problem I just worked through
First I am a rank amateur and often I find that quite the hindrance. Just incase there is some one starting as far back as
I seem to here is the solutions for getting jpm seemingly running smoothly
First following the earlier post

https://groups.google.com/forum/#!topic/mozilla-labs-jetpack/O4gG1VB9yxk
Titled /usr/bin/env: node: No such file or directory
On my system
Xubuntu 14.04
Firefox 39.0.3
with node.js installed

when trying to run jpm init I recieved the error /usr/bin/env: node: No such file or directory
well thanks to  Mikhail Khvoinitsky
 by typing as sudo in the terminal          ln -s /usr/bin/nodejs /usr/local/bin/node

I was able to get a new error   -     

Error: spawn ENOENT
The solution suggested was to run jpm -b /usr/lib64/firefox/firefox runthis did not work for me butericschultz
refined this for ubuntu by noting that 
the path being used by jpm test was /usr/lib64/firefox. 
/usr/lib64/firefox is not where the Firefox binary is on Ubuntu; instead
 it's in /usr/bin/firefox (might be symlinked elsewhere too).

so by running  jpm -b /usr/bin/firefox run

IT WORKED YEA!!!   

ln -s /usr/bin/nodejs /usr/local/bin/node
jpm -b /usr/bin/firefox run

**Comment by kumar303** [comment]
this should be fixed in https://github.com/mozilla-jetpack/jpm/releases/tag/1.1.3
