### ISSUE TITLE
AOM support never landed, need to keep making install.rdf

### ISSUE THREAD

**Issue by jryans** [mozilla-jetpack/jpm#324]
It seems we need to keep including install.rdf for a while / indefinitely.

`jpm` currently removes them if your add-ons min version in `package.json` is 40.

@janodvarko ran into this today. @jsantell, what's the right fix here?

**Comment by jsantell** [comment]
The original plan was for FF to natively load package.json addons, not needing install.rdf and things like that. Fx40 was so far in the future at the time, and we still don't have native addons, so this version number should be 999 right now.

**Comment by jsantell** [comment]
I think a few of [these values](https://github.com/mozilla/jpm/blob/master/lib/settings.js) should be updated...

**Comment by jsantell** [comment]
Closed via #325
