### ISSUE TITLE
Add jpm sign command

### ISSUE THREAD

**Issue by DavidBruant** [mozilla-jetpack/jpm#327]
To sign the addon from the command line.

**Comment by kumar303** [comment]
I'm going to take a stab at a patch for this. Stay tuned...

**Comment by kumar303** [comment]
The signing API itself is getting tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1206158

**Comment by kumar303** [comment]
patch in progress: https://github.com/mozilla-jetpack/jpm/pull/358

**Comment by kumar303** [comment]
the sign command has been completed and is available in 1.0.4 of jpm. Documentation: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign
