### ISSUE TITLE
Please open issue #197 again. It is not closed!

### ISSUE THREAD

**Issue by anaran** [mozilla-jetpack/jpm#341]
Here is what works for me in jpm 1.0.1 today with nightly firefox:

    "icon": "resource://issue-pigeon-at-addons-dot-mozilla-dot-org/data/icon48.png",

Having to use this quoted repetition of the id field in jpm 1.0.1 leaves me speechless.

~~Also, icon48.png displays as a 1 mm square.
icon640.png is a size that blends in nicely with the other icons in about:addons (perhaps that's already scaled down in AMO, I have not checked.~~
(I goofed about the size. 48x48px works nicely. I had kept the transparent background size at 640 which made the foreground image show up so small.)

**Comment by anaran** [comment]
Meanwhile I have put a warning in place at https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#icon

**Comment by freaktechnik** [comment]
I'm not sure if you read why the issue was closed, but see https://bugzilla.mozilla.org/show_bug.cgi?id=1141839 for tracking of the fix for this, which is not in jpm. That was at least the plan back when the issue was closed.

**Comment by anaran** [comment]
Thanks @freaktechnik for the background information.

I missed that bug 1141839, but the workaround suggested there is just accident waiting to happen.

It suggests using a hard-coded icon.png, while package.json might have a different definition for the icon field.

Of course one could extract that information for a better workaround -- but instead I think we need a real fix.

If it's in firefox it will just take even longer to trickle down.
