### ISSUE TITLE
jpm + webextensions

### ISSUE THREAD

**Issue by nschloe** [mozilla-jetpack/jpm#347]
[As of lately](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/), Firefox has adjusted its extension strategy to allow for "chrome-style" extensions aka webextensions. I'm developing [a chrome extension](https://github.com/paperhive/paperhive-frontend) which I'd like to include into Firefox. Manually compiling and installing works smoothly, the question is: 

Can I use jpm to run the app?

**Comment by andymckay** [comment]
Not yet. Would be cool for us to think about how we'd do that though.

**Comment by erikvold** [comment]
+1 This should be easy to do too..

**Comment by erikvold** [comment]
I implemented `jpm` to work with restartless add-ons and old school add-ons here https://github.com/mozilla-jetpack/jpm/commit/9299e1cdbc28f067f1ca90b4f1933da7ff24190b although I'm not sure if this has been busted or not since I was fired @mozilla..

**Comment by askmatey** [comment]
#445

**Comment by kumar303** [comment]
oops, we have two issues about this now. I'm closing this one in favor of https://github.com/mozilla-jetpack/jpm/issues/445 because that has more info, including some ways to develop on web extensions without jpm.
