### ISSUE TITLE
The Promise returned by jpm/lib/post finishes too early

### ISSUE THREAD

**Issue by FayneAldan** [mozilla-jetpack/jpm#369]
`jpm/lib/post` returns a Promise that finishes when the XPI is created, rather than when the XPI is posted.

**Comment by FayneAldan** [comment]
Please fix. I can't figure out any workaround for this since the Promise won't even provide the xpiPath, so I can't even have my script wait for the XPI to be deleted before continuing.

**Comment by FayneAldan** [comment]
Here's my proposal: https://bitbucket.org/Fayne_Aldan/plaza/src/1c083c579998faa90cc41f9adacf923c47c3238f/tasks/jpm.js#-41:66
This would also resolve #370. No credit is needed and you don't need to reserve my code style.

**Comment by kumar303** [comment]
Wrapping `fs.readFile()` in a promise seems like the right approach. Can you submit your change as a [github pull request](https://help.github.com/articles/using-pull-requests/)?
