### ISSUE TITLE
Travis CI build always fails

### ISSUE THREAD

**Issue by FayneAldan** [mozilla-jetpack/jpm#396]
It seems Travis CI building always fails, at least for PRs, because it fails to download Firefox.
```
$ wget `firefox-get -v $FIREFOX_VERSION` -O firefox.tar.bz2 && tar xvf firefox.tar.bz2
No packages foundwget: missing URL
Usage: wget [OPTION]... [URL]...
Try `wget --help' for more options.
The command "wget `firefox-get -v $FIREFOX_VERSION` -O firefox.tar.bz2 && tar xvf firefox.tar.bz2" failed and exited with 1 during .
```

**Comment by kumar303** [comment]
I fixed this in https://github.com/mozilla-jetpack/jpm/pull/397

It looks like the FTP is no longer available. More info: https://ftangftang.wordpress.com/2015/11/17/the-latest-on-firefoxreleaseslatest/

If you rebase on master your PR tests should run.
