### ISSUE TITLE
npm update for `jpm sign`

### ISSUE THREAD

**Issue by brettz9** [mozilla-jetpack/jpm#400]
Hi,

If `jpm sign` will allow us to build signed .xpi add-ons, it would be great to have an npm release of this as soon as possible... (and if Firefox won't allow XPIs otherwise, I'm wondering why the default behavior is not to have this checking done automatically).

**Comment by kumar303** [comment]
Firefox will allow unsigned XPIs for development. You can run either the [Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) or [Nightly](https://nightly.mozilla.org/), go to `about:config`, and set the `xpinstall.signatures.required` preference to `false`; signing will not be enforced.

The `jpm sign` command is really only necessary for automatic distribution, such as through [TravisCI](https://travis-ci.org/) or something automated like that. When signing is *enforced* in the release version of Firefox (this will happen in version 44), you can still use an unbranded version of the latest Firefox to test your add-on.

With that said, we aren't quite ready to release the signing command on npm but it's very close. We expect to close the remaining bugs this week and push a release.

**Comment by brettz9** [comment]
I see, great, thanks!
