### ISSUE TITLE
jpm sign broken by merged #394

### ISSUE THREAD

**Issue by micgro42** [mozilla-jetpack/jpm#401]
Pullrequest #394 broke usage of `jpm sign` without a custom .xpi
Running `jpm sign --api-key [...] --api-secret [...]` now always displays the following error-message:
```
JPM [info] Starting jpm sign on [...]

  error: missing required option `--api-key'
  error: missing required option `--api-secret'

JPM [error] FAIL
```
Checking out commit 221dfd8 solved the issue for me and `jpm sign` works as expected.

**Comment by kumar303** [comment]
oops, should be fixed now. Thanks!
