### ISSUE TITLE
jpm [watch]post: ReferenceError: when is not defined

### ISSUE THREAD

**Issue by groovecoder** [mozilla-jetpack/jpm#435]
My add-on code builds fine with `jpm xpi` and runs fine with `jpm run`. But `post` and `watchpost` throw a `ReferenceError`

Steps to reproduce:
```
lcrouch:fx-doiuse lcrouch$ jpm -V
1.0.3
```
```
lcrouch:fx-doiuse lcrouch$ jpm post --post-url http://localhost:8888/
JPM [info] Starting jpm post on doiuse
Creating XPI
JPM [info] XPI created at /Users/lcrouch/code/fx-doiuse/@fx-doiuse-0.0.1.xpi (37ms)
Created XPI at /Users/lcrouch/code/fx-doiuse/@fx-doiuse-0.0.1.xpi
[ReferenceError: when is not defined]
```
```
lcrouch:fx-doiuse lcrouch$ jpm watchpost --post-url http://localhost:8888/
JPM [info] Starting jpm watchpost on doiuse
Creating XPI
JPM [info] XPI created at /Users/lcrouch/code/fx-doiuse/@fx-doiuse-0.0.1.xpi (43ms)
Created XPI at /Users/lcrouch/code/fx-doiuse/@fx-doiuse-0.0.1.xpi
[ReferenceError: when is not defined]
```

This seems to break my Firefox Extension Auto-Installer, so I don't see my file changes auto-updating in my Firefox. :cry:

**Comment by groovecoder** [comment]
Note: I don't see this error when I switch to using `master` branch. So maybe this is already fixed?

**Comment by kumar303** [comment]
What version were you on? Yeah, it was fixed on master in https://github.com/mozilla-jetpack/jpm/commit/6ce28ab54905a853c6e96b9fa58773e0f8587a50 but it should also be in the latest npm release.

**Comment by groovecoder** [comment]
```
lcrouch:fx-doiuse lcrouch$ jpm -V
1.0.3
```
Yup. I needed to re-install jpm to get 1.0.4.
