### ISSUE TITLE
 xpi build with jpm cannot be installed on android

### ISSUE THREAD

**Issue by jmozmoz** [mozilla-jetpack/jpm#444]
This is a copy of a bug report at https://bugzilla.mozilla.org/show_bug.cgi?id=1223155

If I create an xpi by the current version of jpm (1.0.3) the resulting xpi cannot be installed on Android:

If I upload the created xpi (in the beta channel) on addons.mozilla.org, the platform Android cannot not be selected. If I select all platforms and the try to install it on Android the button to install is grayed out. Also if I move the xpi to the sdcard and try to install it directly, nothing is happening.

If I use cfx --force-mobile xpi (cfx version 1.17) the resulting xpi can be uploaded as Android version to addons.mozilla.org and can be installed on Android (with Firefox 42.0). With Firefox Beta (43.0) it is still not possible to install it on Android (there is a message saying that a newer version of Firefox is necessary, which is obviously non-sense, because it works with an older version).

The link to the addon source code is https://github.com/jmozmoz/tabpreloader

**Comment by kumar303** [comment]
You need to add `fennec` to your `engines` in [package.json](https://github.com/jmozmoz/tabPreLoader/blob/master/package.json) like this:
````
"engines": {
    "firefox": ">=38.0a1",
    "fennec": ">=38.0a1"
  }
````
More info: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json

I think `--force-mobile` was just a hack in cfx that added in the fennec application ID.

**Comment by jmozmoz** [comment]
@kumar303 thank you for your comment. Adding the engines for both firefox and fennec solved the problem. I added this information to https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx_to_jpm

**Comment by kumar303** [comment]
Nice! Good call on the migration docs
