### ISSUE TITLE
Add support for WebExtensions API

### ISSUE THREAD

**Issue by askmatey** [mozilla-jetpack/jpm#445]
- [ ] Allow `jpm` to run Firefox add-ons using the [WebExtensions API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)
- [ ] Create a new tool to run Firefox add-ons using the [WebExtensions API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions)

Example:

```sh
jpm run nightly my_webextension@firefox.com.xpi --prefs firefox-webextension-env.json
```

Custom set user preferences (`firefox-webextension-env.json`):

```json
{
  "xpinstall.signatures.required": "false"
}
```

**Comment by askmatey** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1234243

**Comment by andymckay** [comment]
Would it make more sense to make a new tool for WebExtensions?

**Comment by askmatey** [comment]
@andymckay I have posted a message to the dev-addons mailing list.

@jsantell bump

**Comment by Mte90** [comment]
We have discussed that problem in the mailing list in november: https://mail.mozilla.org/pipermail/dev-addons/2015-November/000150.html
We need that to promote that new API and create new extensions.

**Comment by kumar303** [comment]
@Mte90 until we have command line support, you can load a web extension from your local source directory which means you don't have to reinstall it or restart Firefox as you develop on it. It just landed on nightly and is available from `about:debugging` https://bugzilla.mozilla.org/show_bug.cgi?id=1231129

**Comment by kumar303** [comment]
Summary of my response to this on the mailing list:

I think it would make sense to create a new command line tool to develop web extensions with rather than patch jpm. This would allow us to reinvent the web extension development flow which has received much better platform support since jpm was first written.

**Comment by Mte90** [comment]
So the first problem is resolved internally in firefox :-)
There is not docs in internet about that page actually but this resolve many problem!

**Comment by kumar303** [comment]
The `about:debugging` page is a brand new thing, we hope to have docs available shortly. I agree about command line support but until then you just have to open the browser once (at the start of your day), install your directory of code, and you can keep hacking throughout the day. However, I think there are edge cases in here that still need to be resolved.

**Comment by kumar303** [comment]
> So the first problem is resolved internally in firefox :-)

Oh whoops, this was the public thread I was referring to https://mail.mozilla.org/pipermail/dev-addons/2015-December/000230.html (I thought the thread linked above was this, heh)

**Comment by kumar303** [comment]
> we need a command line support for use it with autoload of changes!

Agreed!

We decided to create a new tool: https://github.com/mozilla/web-ext
