### ISSUE TITLE
Please support http proxy servers for jpm. 

### ISSUE THREAD

**Issue by jnurthen** [mozilla-jetpack/jpm#446]
jpm sign and other such commands seem intended to support corporate users who are normally behind proxy servers. As such jpm needs to support their configurations.

**Comment by kumar303** [comment]
Do you think simply specifying a proxy server [to request](https://github.com/request/request#proxies) would work for your case? Could you try editing [this line](https://github.com/mozilla-jetpack/jpm/blob/master/lib/amo-client.js#L365) to see if it works for you? I'm guessing something like:
````
requestConf.proxy = 'https://<your-proxy>';
````
So, in other words, I'm not asking for a patch but just a proof to see if the `proxy` option works for what you need.

**Comment by kumar303** [comment]
and you could run it with `jpm --verbose sign ...` to get more info

**Comment by jnurthen** [comment]
That seemed to work for the upload great. I set
requestConf.proxy = 'http://myproxy:proxyport'; 
and the upload completed.

I got a timeout error eventually but it may have been that the addon took a while to complete the validation. It was available on MDN so the upload part completed ok.

**Comment by kumar303** [comment]
ok, thanks, we will add a `--proxy` command line option for this.

**Comment by jnurthen** [comment]
Thanks - that would be great.

**Comment by kumar303** [comment]
This depends on https://github.com/mozilla-jetpack/jpm/issues/519 and https://github.com/mozilla/sign-addon/issues/49

**Comment by ingoe** [comment]
+1

**Comment by vanthoom** [comment]
Hi whats the current status and plan to suport this?

**Comment by kumar303** [comment]
No plans yet. I can mentor a patch to sign-addon for it. This is step 1.

**Comment by kumar303** [comment]
I was making other changes to `sign-addon` so I started a patch for proxy support: https://github.com/mozilla/sign-addon/pull/120 On the JPM side, we will need more work thought, such as https://github.com/mozilla-jetpack/jpm/issues/519

**Comment by kumar303** [comment]
The new `--api-proxy` option is available now in jpm 1.3.0 https://www.npmjs.com/package/jpm

@ingoe thanks again for coming back to this patch!

**Comment by vvijayabhanu** [comment]
Hi

Is this apiproxy fields support a proxy machine that requires username and password
