### ISSUE TITLE
JPM not Working/Detecting with Firefox 64 Bit

### ISSUE THREAD

**Issue by yuva9882** [mozilla-jetpack/jpm#451]
JPM is not working/detecting with 64 bit Firefox. Please fix it.

---------------------------------------------------------------------------------
JPM [info] Starting jpm test on
Creating XPI
JPM [info] XPI created at C:\Users\AppData\Local\Temp\jid1-@jetpack-.xpi (177ms)
Created XPI at C:\Users\AppData\Local\Temp\jid1-=@jetpack-.xpi
JPM [info] Creating a new profile
JPM [error] No Firefox binary found at null
JPM [error] Specify a Firefox binary to use with the -b flag.
JPM [error] Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT

---------------------------------------------------------------------------------

Please fix it asap.

**Comment by akisman** [comment]
Although it doesn't automatically detect the 64bit version, you can use the -b or --binary option(```jpm run -b "C:\Program Files\Mozilla Firefox\firefox.exe"``` in Windows) or set up the JPM_FIREFOX_BINARY environmental variable(you may need to do a restart after in this case) as mentioned in the [Docs ](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Selecting_a_browser_version).

**Comment by kumar303** [comment]
>> JPM [error] Error: spawn C:\Program Files (x86)\Mozilla Firefox\firefox.exe ENOENT

This means that jpm guessed but could not find the path to your Firefox executable. As mentioned in the comment above, you need to run it with `-b`. This doesn't appear to be a bug in jpm with the info provided.

**Comment by kumar303** [comment]
However, the ENOENT message could be better

**Comment by kumar303** [comment]
Well, nevermind. It tells you in the error output that it can't find Firefox already.

**Comment by onikienko** [comment]
Why do not try to find 64 FF version automatically if x86 not detected?

**Comment by kumar303** [comment]
Yes, if it's possible to detect it in a reliable way then this would be a welcome patch to jpm. If someone has an idea for this, I can re-open the issue. I assumed it would not be possible to detect it in a reliable way.
