### ISSUE TITLE
Can't sign an add-on twice via "jpm sign" with one ID

### ISSUE THREAD

**Issue by zeird** [mozilla-jetpack/jpm#454]
I've been using AMO add-on signing API to sign my unlisted add-on. Then I tried to sign a new version (.xpi file) via `jpm sign` (version `1.0.4`). It failed with the following error:

> JPM [error] Server response: Duplicate add-on ID found. ( status: 400 )

Then I created a new test add-on, signed it once successfully, increased it's version and for the second time it failed with the same error:

> JPM [error] Server response: Duplicate add-on ID found. ( status: 400 )

That happens because

> Under the hood, jpm sign creates an unlisted add-on inside addons.mozilla.org

as said in [jpm article on MDN](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign). Deleting unlisted add-on is not an options because

> Deleting your add-on will permanently remove it from the site and prevent its GUID from being submitted ever again, even by you.

Which makes current version of `jpm sign` completely unusable. Looks like a blocker to me.

I think `jpm` should fail only if an add-on ID doesn't belong to api-key owner, and use it without any issues if it does.

**Comment by kumar303** [comment]
What command are you running? Are you using the `--xpi` option?

The same bug as https://github.com/mozilla-jetpack/jpm/issues/450 may be causing this.

If possible, could you provide more information. Either of the following would help:
- re-run the command with `jpm --verbose` and attach a text file of the output (with your API credentials removed from the command)
- attach an XPI that causes the duplicate ID message. You'll have to change the extension from .xpi to .zip so that github will let you attach it.

**Comment by zeird** [comment]
> Are you using the --xpi option?

Yes. I've rerun the command with `--verbose` key and now the root of the issue seems to be pretty obvious to me:

> The same bug as #450 may be causing this.

You're right. The absence of `id` field in `package.json` causes `jpm sign` to use `null` in API url instead of add-on's id from `install.rdf`.

However, absence of `id` field in `package.json` isn't a problem if there wasn't unlisted add-on with that id before.

I guess I don't need to attach text file of the output or .xpi anymore.

**Comment by kumar303** [comment]
> However, absence of id field in package.json isn't a problem if there wasn't unlisted add-on with that id before.

Yes, correct. It is a bug in how jpm is detecting version numbers. It will be fixed in #450 so I'll close this one. Thanks for the bug report.
