### ISSUE TITLE
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.6.20.2/

### ISSUE THREAD

**Issue by uri-wisestamp** [mozilla-jetpack/jpm#455]
JPM [info] Creating updateRDF...
Created XPI at C:\Users\uriwise\AppData\Local\Temp\tmp-unsigned-xpi-2700H4lkn8lV3Zli\test-1@wisestamp.com-4.6.20.2.xpi
JPM [info] Created XPI for signing: C:\Users\uriwise\AppData\Local\Temp\tmp-unsigned-xpi-2700H4lkn8lV3Zli\test-1@wisestamp.com-4.6.20.2.xpi
JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.6.20.2/',
  formData:
   { upload:
      { _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        path: 'C:\\Users\\uriwise\\AppData\\Local\\Temp\\tmp-unsigned-xpi-2700H4lkn8lV3Zli\\test-1@wisestamp.com-4.6.20.2.xpi',
        fd: null,
        flags: 'r',
        mode: 438,
        start: undefined,
        end: undefined,
        autoClose: true,
        pos: undefined } },
  headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
JPM [debug] [API] <- { headers:
   { allow: 'GET, PUT, HEAD, OPTIONS',
     'content-type': 'application/json',
     date: 'Wed, 30 Dec 2015 14:42:20 GMT',
     server: 'nginx',
     'set-cookie': '<REDACTED>',
     'strict-transport-security': 'max-age=31536000',
     vary: 'Accept, X-Mobile, User-Agent',
     'www-authenticate': 'JWT realm="api"',
     'x-frame-options': 'DENY',
     'content-length': '51',
     connection: 'Close' },
  response: { detail: 'Incorrect authentication credentials.' } }
JPM [error] FAIL
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.6.20.2/

status: 401
response: {"detail":"Incorrect authentication credentials."}
headers: {"allow":"GET, PUT, HEAD, OPTIONS","content-type":"application/json","date":"Wed, 30 Dec 2015 14:42:20 GMT","server":"nginx","set-cookie":["multidb_pin_writes=y; expires=Wed, 30-Dec-2015 14:42:35 GMT; Max-Age=15; Path=/"],"strict-transport-security":"max-age=31536000","vary":"Accept, X-Mobile, User-Agent","www-authenticate":"JWT realm=\"api\"","x-frame-options":"DENY","content-length":"51","connection":"Close"}

    at C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\lib\amo-client.js:85:13
    at tryCatchReject (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:845:30)
    at runContinuation1 (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:804:4)
    at Fulfilled.when (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:592:4)
    at Pending.run (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\makePromise.js:483:13)
    at Scheduler._drain (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\Scheduler.js:62:19)
    at Scheduler.drain (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\node_modules\when\lib\Scheduler.js:27:9)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)

**Comment by kumar303** [comment]
This error means you're API credentials are incorrect. It's working as expected so I'm going to close the issue. Double check the values of `--api-key` and `--api-secret` and if they still don't work, regenerate your credentials on the DevHub.

From what you described in the original thread (https://discourse.mozilla-community.org/t/validation-took-too-long-to-complete/6178) I think what you pasted here is a different error.

**Comment by uri-wisestamp** [comment]
What is the problem with our credentials? I downloaded them from https://addons.mozilla.org/en-US/developers/addon/api/key/ . We already released new versions for Chrome and Safari last week, only Firefox we can't release because of this bug.

**Comment by uri-wisestamp** [comment]
I tried again now and it worked, so I guess this bug was something on the server side which was fixed.
