### ISSUE TITLE
'jpm sign' timing out

### ISSUE THREAD

**Issue by robertknight** [mozilla-jetpack/jpm#457]
I made an initial pass at setting up automated signing of my open source password manager for Firefox (see https://github.com/robertknight/passcards/issues/60 ) . In testing I encountered sporadic timeouts of the 'jpm sign' tool.

````
Error: Validation took too long to complete; last status: {"active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/passcards%40robertknight.github.io/versions/0.3.951/uploads/d16c6b06a01c4d698e7833785388e3fe/","files":[],"passed_review":false,"pk":"d16c6b06a01c4d698e7833785388e3fe","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":false,"warnings":57,"compatibility_summary":{"notices":0,"errors":0,"warnings":0},"passed_auto_validation":false,"ending_tier":5,"messages":[{"context":n...

    at null._onTimeout (/home/travis/build/robertknight/passcards/node_modules/jpm/lib/amo-client.js:174:14)

    at Timer.listOnTimeout (timers.js:89:15)
```

I haven't yet established whether the process would succeed if given a longer timeout or if a different type of failure is happening. I have seen successful signing take >40s though.

**Comment by robertknight** [comment]
Update: I received an email afterwards indicating that signing was successful for this build, so it appears that jpm's default timeout is simply too short.

**Comment by andymckay** [comment]
This isn't a bug in jpm sign itself, I'm not sure the value of setting the timeout longer.

**Comment by robertknight** [comment]
This issue makes `jpm sign` unfortunately fundamentally not that useful for what is presumably one of its main intended purposes.

I don't suppose the Mozilla team managing the validation system have data on eg. the 50th, 95th, 99th percentile times for validation that might help here?

**Comment by bgiaccio** [comment]
@andymckay,
The value of setting a longer timeout is to wait longer if your plugin consistently takes longer to sign thereby allowing you to retrieve the signed file

In my case we sign as part of our automated build process, yesterday on 4 runs of the build the jpm sign timeout'd out twice, resulting in 2 failed builds.

Short of waiting longer I believe the only other recourse would be:
1. let jpm sign fail
2. inspect the output to ensure it failed for timeout
3. go and scrape the versions page to get the latest version
4. go to the latest version page and scrape that page to get the dowload URL
5. download the xpi

**Comment by iubica** [comment]
Same problem happened with my add-on. Executing the jpm sign, I get the error below.

$ jpm sign --api-key ${AMO_API_KEY} --api-secret ${AMO_API_SECRET}

Validating add-on [............................................................]JPM [error] FAIL
Error: Validation took too long to complete; last status: {"active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/jid1-PWvb5d6eoY4YYQ%40jetpack/versions/1.0.4/uploads/f4ea466df08f4b56bf89cf831cd44efe/","files":[],"passed_review":false,"pk":"f4ea466df08f4b56bf89cf831cd44efe","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":false,"warnings":1,"compatibility_summary":{"notices":0,"errors":0,"warnings":0},"passed_auto_validation":true,"ending_tier":5,"messages":[{"file":"index.js","e...
    at null._onTimeout (C:\Users\andrei\AppData\Roaming\npm\node_modules\jpm\lib\amo-client.js:174:14)
    at Timer.listOnTimeout (timers.js:92:15)

I can't figure out how to go around it. Manually signing through developer hub works, but I can't download the signed XXX-fx.xpi file.

**Comment by iubica** [comment]
Finally, after running it five or six times, signing worked. Ugh!
