### ISSUE TITLE
jpm sign: Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by arcao** [mozilla-jetpack/jpm#458]
Hello guys,

I am trying to sign existing xpi file ([firenyx-0.1.14.2014093001.zip](https://github.com/mozilla-jetpack/jpm/files/76180/firenyx-0.1.14.2014093001.zip)) with following command:
```
jpm sign -v --api-key user:613385:367 --api-secret 0318... --xpi firenyx-0.1.14.2014093001.xpi
```

But result is EEXIST error:
```
JPM [info] verbose set
JPM [error] FAIL
Error: EEXIST: file already exists, mkdir 'C:\Users\Martin\AppData\Local\Temp\tmp-2492BkWVhH1SmxAM\content'
    at Error (native)
```

Any idea what I am doing wrong?

node.js version: 4.2.4
jpm version: 1.0.4

**Comment by PikachuEXE** [comment]
I have the same issue
node.js: 4.3.0
jpm: 1.0.5

**Comment by kumar303** [comment]
@arcao thanks for posting a zip file and sorry I missed this when you first submitted the issue. I can reproduce it. I will take a look.

**Comment by PikachuEXE** [comment]
I have try latest version (`1.0.6`) and still fail

### Log
```
$ jpm sign --verbose --api-key=user:12345 --api-secret=aaaa--xpi=tabkit2_0.12.5.xpi

JPM [info] verbose set
JPM [error] FAIL
Error: EEXIST: file already exists, mkdir 'T:\TEMP\tmp-extracted-xpi-31984HePYyLswy4bm\content'
    at Error (native)
```

**Comment by kumar303** [comment]
I may not have bandwidth to work on this for a while. If you download the zip it is easy to reproduce the bug so it should be simple to fix (maybe).
