### ISSUE TITLE
Validation took too long to complete

### ISSUE THREAD

**Issue by uri-wisestamp** [mozilla-jetpack/jpm#459]
Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]JPM [debug] [API] <- { headers:
   { allow: 'GET, PUT, HEAD, OPTIONS',
     'content-type': 'application/json',
     date: 'Tue, 05 Jan 2016 14:49:33 GMT',
     server: 'nginx',
     'strict-transport-security': 'max-age=31536000',
     vary: 'Accept, X-Mobile, User-Agent',
     'x-backend-server': 'ip-172-31-45-57',
     'x-frame-options': 'DENY',
     'transfer-encoding': 'chunked',
     connection: 'Close' },
  response:
   { active: false,
     automated_signing: true,
     url: 'https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.7.20.1/uploads/90bbdad0fa774b0f88fd8558231ce53a/',
     files: [],
     passed_review: false,
     pk: '90bbdad0fa774b0f88fd8558231ce53a',
     processed: true,
     reviewed: false,
     valid: true,
     validation_results:
      { errors: 0,
        success: false,
        warnings: 37,
        compatibility_summary: [Object],
        passed_auto_validation: false,
        ending_tier: 5,
        messages: [Object],
        message_tree: [Object],
        detected_type: 'extension',
        signing_summary: [Object],
        notices: 2,
        signing_ignored_summary: [Object],
        metadata: [Object] },
     validation_url: 'https://addons.mozilla.org/en-US/developers/upload/90bbdad0fa774b0f88fd8558231ce53a',
     version: '4.7.20.1' } }
Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.7.20.1/uploads/90bbdad0fa774b0f88fd8558231ce53a/',
  headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]JPM [debug] [API] <- { headers:
   { allow: 'GET, PUT, HEAD, OPTIONS',
     'content-type': 'application/json',
     date: 'Tue, 05 Jan 2016 14:49:36 GMT',
     server: 'nginx',
     'strict-transport-security': 'max-age=31536000',
     vary: 'Accept, X-Mobile, User-Agent',
     'x-backend-server': 'ip-172-31-45-57',
     'x-frame-options': 'DENY',
     'transfer-encoding': 'chunked',
     connection: 'Close' },
  response:
   { active: false,
     automated_signing: true,
     url: 'https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.7.20.1/uploads/90bbdad0fa774b0f88fd8558231ce53a/',
     files: [],
     passed_review: false,
     pk: '90bbdad0fa774b0f88fd8558231ce53a',
     processed: true,
     reviewed: false,
     valid: true,
     validation_results:
      { errors: 0,
        success: false,
        warnings: 37,
        compatibility_summary: [Object],
        passed_auto_validation: false,
        ending_tier: 5,
        messages: [Object],
        message_tree: [Object],
        detected_type: 'extension',
        signing_summary: [Object],
        notices: 2,
        signing_ignored_summary: [Object],
        metadata: [Object] },
     validation_url: 'https://addons.mozilla.org/en-US/developers/upload/90bbdad0fa774b0f88fd8558231ce53a',
     version: '4.7.20.1' } }
Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.7.20.1/uploads/90bbdad0fa774b0f88fd8558231ce53a/',
  headers: { Authorization: '<REDACTED>', Accept: 'application/json' } }
Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  ]Validating add-on [ .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . ]Validating add-on [  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .]Validating add-on [..........................................................................................................................................]JPM [error] FAIL
Error: Validation took too long to complete; last status: {"active":false,"automated_signing":true,"url":"https://addons.mozilla.org/api/v3/addons/test-1%40wisestamp.com/versions/4.7.20.1/uploads/90bbdad0fa774b0f88fd8558231ce53a/","files":[],"passed_review":false,"pk":"90bbdad0fa774b0f88fd8558231ce53a","processed":true,"reviewed":false,"valid":true,"validation_results":{"errors":0,"success":false,"warnings":37,"compatibility_summary":{"notices":0,"errors":0,"warnings":0},"passed_auto_validation":false,"ending_tier":5,"messages":[{"file":"lib/content/sr...
    at null._onTimeout (C:\Users\uriwise\AppData\Roaming\npm\node_modules\jpm\lib\amo-client.js:174:14)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by andymckay** [comment]
This isn't a bug in jpm, if you feel this is a valid bug in AMO, you can file it over there. Sometimes it takes a while.

**Comment by pokono** [comment]
I understand, but this makes jpm unreliable.

**Comment by freaktechnik** [comment]
Note that JPM should no longer be considered reliable, especially with further changes on the AMO side. You should switch to using newer tooling like web-ext or sign-addon that it uses.
