### ISSUE TITLE
Can't detect x64 Firefox

### ISSUE THREAD

**Issue by steelywing** [mozilla-jetpack/jpm#463]
Can't auto detect Firefox binary in x64 version, it point to " C:\Program Files (x86)\Mozilla Firefox\firefox.exe"

**Comment by kumar303** [comment]
I don't think there's an easy way to detect program locations on Windows but I'm open to a pull request if someone has one. Until then, I'm closing the issue.

To workaround this, you can use the `--binary` option as [documented](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Selecting_a_browser_version).
