### ISSUE TITLE
jpm sign existing xpi results error

### ISSUE THREAD

**Issue by arieljannai** [mozilla-jetpack/jpm#471]
I'm getting `error: 'Duplicate add-on ID found.'` when trying to sign an existing xpi with jpm sign.
I'm running `jpm sign --api-key key --api-secret secret --xpi extension.xpi`

I've added `verbose` and saw that line:
`JPM [debug] [API] -> { url: 'https://addons.mozilla.org/api/v3/addons/null/versions/undefined/'`,
It's trying to access null as id and undefined as version.

I don't know if it's possible, but I'm using it on a xul based plugin. If it's not possible (which I don't see a reason for, except that the info is in install.rdf and not in package.json) - I should get a relevant error I guess.

**Comment by kumar303** [comment]
Can you upgrade jpm to 1.0.5 and try again? This was just fixed in https://github.com/mozilla-jetpack/jpm/issues/465

**Comment by arieljannai** [comment]
Awesome, thanks!
Will it also support packing non SDK add-ons?

**Comment by kumar303** [comment]
> Will it also support packing non SDK add-ons?

No, there are no plans to support this. You should be able to do it on the command like:
````
cd /path/to/non-sdk-addon
zip -r ../name-of-addon.xpi .
````

**Comment by arieljannai** [comment]
> No, there are no plans to support this. You should be able to do it on the command line like:

That's what I did, just wanted to knew :smile:
