### ISSUE TITLE
Allow arbitrary engines

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-jetpack/jpm#473]
I suggest allowing arbitrary engines that are formatted as UUID. Those would still be included into the install.rdf. This would allow developers to generated extensions that also work in other not officially supported applications without having to always modify the generated xpi, or maybe even use jpm run with those applications.

**Comment by kumar303** [comment]
That seems reasonable. Could you provide an example of a specific engine (application) you're trying to target? Just curious.

**Comment by freaktechnik** [comment]
I'm writing an extension for Instantbird with the SDK (freaktechnik/twitch-provider). Yes, instantbird doesn't properly handle everything yet, but that's WIP. Instantbird's UUID is `{33cb9019-c295-46dd-be21-8c4936574bee}`.

I'd be willing to write up a patch. I've looked at the code in question some time ago and it seemed pretty straight forward.

**Comment by kumar303** [comment]
ok, sounds like a good patch. I'm surprised it doesn't let you specify arbitrary engines already.
