### ISSUE TITLE
jpm@1.0.5 does not compress files when packing .xpi (with update.rdf)

### ISSUE THREAD

**Issue by jc3213** [mozilla-jetpack/jpm#474]
Environment: 
Win10 64bit 2015LTSB, nodejs 5.5.0, jpm 1.0.5

Information: 
The result is that the compress ratio of the packed xpi by jpm 1.0.5 is 100%, which means none of the files have been compressed

I've installed jpm 1.0.4 using npm install jpm@1.0.4 -g and then packed my-addon.xpi via jpm xpi. The compress ratio is about 42% (recognized by winrar)

I have install/uninstall nodejs, run npm install jpm -g and npm uninstall jpm -g for many times...but nothing changes, I wonder if there is something wrong with my build environment or this is the bug of jpm 1.0.5?

**Comment by kumar303** [comment]
That seems bizarre. Is the XPI a valid XPI that you can install? Could you attach a zip of the source (if possible) so that I could unzip it and try running `jpm xpi` to reproduce the issue?

**Comment by jc3213** [comment]
Yes, the XPI is valid to install and is able to be signed by jpm sign. and I've asked other people to try that, they also get uncompressed XPI file.

**Comment by jc3213** [comment]
Github keeps warning that "Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. "

Would you mind if you can download from https://github.com/jc3213/SimpleProxy/releases/download/2.0.1/myaddon.ZIP here?

**Comment by kumar303** [comment]
Thanks, I downloaded it and will take a look tomorrow.

> the maxVersion is only 43.0, but it is now 44.0 in release

Version incompatibility is just a relic of the past. It's not enforced anywhere in Firefox anymore to my knowledge.

**Comment by jc3213** [comment]
Yes, I know,but it's annoying  when I visit Manage My Submission on AMO

**Comment by kumar303** [comment]
annoying in what way? Do you see a warning? That might be something we could fix easily.

**Comment by kumar303** [comment]
ok, I see what you mean. I can also see 0% compression with `unzip` on an XPI created with jpm from the master repo branch. If I switch to the `1.0.4` tag I see 62% (as expected). Comparison: 

````
$ git checkout master
$ npm install
...
$ pushdir ~/Downloads/Simple\ Proxy
$ jpm xpi
...
$ unzip -lv simpleproxy\@jc3213.github-2.0.2.xpi
Archive:  simpleproxy@jc3213.github-2.0.2.xpi
 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
       0  Stored        0   0%  01-28-16 11:58  00000000  content/
       0  Stored        0   0%  01-28-16 11:58  00000000  locale/
    3895  Stored     3895   0%  01-28-16 11:58  e5a2539e  package.json
    7651  Stored     7651   0%  01-28-16 11:58  17e4701b  LICENSE
    2488  Stored     2488   0%  01-28-16 11:58  19a4930d  icon.png
    1239  Stored     1239   0%  01-28-16 11:58  69773d6f  locale/en-US.properties
    1171  Stored     1171   0%  01-28-16 11:58  d6953f4a  locale/zh-CN.properties
    1555  Stored     1555   0%  01-28-16 11:58  8ee61a0e  locale/ja.properties
    7273  Stored     7273   0%  01-28-16 11:58  a027a2b2  content/main.js
    1499  Stored     1499   0%  01-28-16 11:58  0115630c  install.rdf
     593  Stored      593   0%  01-28-16 11:58  48b24589  bootstrap.js
--------          -------  ---                            -------
   27364            27364   0%                            11 files

...

$ git checkout 1.0.4
$ npm install
...
$ pushdir ~/Downloads/Simple\ Proxy
$ jpm xpi
....
$ unzip -lv simpleproxy\@jc3213.github-2.0.2.xpi
Archive:  simpleproxy@jc3213.github-2.0.2.xpi
 Length   Method    Size  Ratio   Date   Time   CRC-32    Name
--------  ------  ------- -----   ----   ----   ------    ----
       0  Stored        0   0%  01-28-16 12:16  00000000  content/
       0  Stored        0   0%  01-28-16 12:16  00000000  locale/
     593  Defl:N      365  38%  01-28-16 12:16  48b24589  bootstrap.js
    1499  Defl:N      735  51%  01-28-16 12:16  0115630c  install.rdf
    7651  Defl:N     2617  66%  01-28-16 12:16  17e4701b  LICENSE
    3895  Defl:N      826  79%  01-28-16 12:16  e5a2539e  package.json
    2488  Defl:N     2493  -0%  01-28-16 12:16  19a4930d  icon.png
    7273  Defl:N     2095  71%  01-28-16 12:16  a027a2b2  content/main.js
    1239  Defl:N      356  71%  01-28-16 12:16  69773d6f  locale/en-US.properties
    1171  Defl:N      399  66%  01-28-16 12:16  d6953f4a  locale/zh-CN.properties
    1555  Defl:N      443  72%  01-28-16 12:16  8ee61a0e  locale/ja.properties
--------          -------  ---                            -------
   27364            10329  62%                            11 files
````

**Comment by kumar303** [comment]
I'm attaching the [Simple_Proxy.zip](https://github.com/mozilla-jetpack/jpm/files/108789/Simple_Proxy.zip) source for safe keeping.

**Comment by kumar303** [comment]
@rpl this looks related to the update.rdf changes from https://github.com/mozilla-jetpack/jpm/pull/448 Could you take a look?

**Comment by jc3213** [comment]
The image about AMO warning  @kumar303 
![amo compatibility warning](https://cloud.githubusercontent.com/assets/8744936/12662969/df570058-c65e-11e5-9a45-43427574fe61.png)

**Comment by kumar303** [comment]
the warning should be fixed in https://github.com/mozilla/olympia/issues/1548

**Comment by jc3213** [comment]
Oh, there's another problem that I nearly forget...

The update.rdf generated by JPM can't be signed by McCoy Tool to generate a signature for hosting on a none SSL server. While updateKey in package.json will generate install.rdf with updateKey though.

If you sign the update.rdf with McCoy, nothing will be changed.Then if you verify with McCoy, McCoy shows that "All update information verified",But if you try to update with that update.rdf, Firefox will warn about that the signature doesn't match, and the new version won't be updated.

I wonder if this is the problem with McCoy or JPM. Now I have to modify the update.rdf then sign it with McCoy manually. I wonder if there will be any chance that JPM will have the ability to automatically sign the update.rdf?? (since it generate it automatically if updateLink is set)

**Comment by uFFFD** [comment]
yes it was introduced in #448:
https://github.com/mozilla-jetpack/jpm/blob/c4b809a74e30c44af0e18f58a4e29e38f3579505/lib/xpi/utils.js#L133

https://stuk.github.io/jszip/documentation/api_jszip/generate.html
options.compression defaults to `STORE` (no compression)

**Comment by kumar303** [comment]
Ah! ok, thanks. I don't know if there are other things that need changing but this definitely sounds like a start.

@rpl could you review this patch (if you are back from fosdem)? https://github.com/mozilla-jetpack/jpm/pull/488
