### ISSUE TITLE
Where does jpm takes my email address from?

### ISSUE THREAD

**Issue by arieljannai** [mozilla-jetpack/jpm#480]
I receive update emails to my mozilla addons developer account, and also to my regular mail.
Where does jpm takes my other email from? git? npm?

**Comment by kumar303** [comment]
You can manage your email and notification preferences by logging into https://addons.mozilla.org/en-US/firefox/

I think jpm gets your email from the `author` key in [package.json](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json#Key_reference).

**Comment by arieljannai** [comment]
weird, non of them mentions my email address.

**Comment by kumar303** [comment]
You could check the `install.rdf` within the final XPI. I think AMO ultimately gets it from there.

**Comment by arieljannai** [comment]
not there :sweat_smile: 
I'll just live with the unkown
