### ISSUE TITLE
JPM should ignore XPIs by default

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-jetpack/jpm#481]
JPM currently doesn't have `*.xpi` in its default ignore set, which means it will package the last built xpi in the newly built xpi.

**Comment by jc3213** [comment]
You can set '*.xpi' to .jpmignore

**Comment by freaktechnik** [comment]
@jc3213 yes, however jpm has a default set that should be ok for standard use, so you don't need a .jpmignore for every extension.

**Comment by kumar303** [comment]
Sounds like a good idea. I know that sub-XPIs are technically supported (on AMO at least) but I don't really know why. I can't find any docs about it so I wouldn't worry about it.

**Comment by freaktechnik** [comment]
Oh, it seems JPM tries to ignore the XPI: it ignores addonID*.xpi, which should ignore all XPIs generated for the extension, which should normally work. I misread that code and somehow messed that function up in my tests.

**Comment by freaktechnik** [comment]
Actually, signed XPIs don't necessarily have the same naming pattern as using jpm xpi. However jpm will only ignore the pattern jpm xpi uses.

**Comment by freaktechnik** [comment]
@kumar303 is the resulting format for signed XPIs always lower-cased title with spaces replaced by `_` and then version + platform info? Is there more escaping happening?

**Comment by kumar303** [comment]
Yes, this is how AMO consistently creates signed files.
