### ISSUE TITLE
Some kind of l10n key like &string; in options.xul for options using the same translation

### ISSUE THREAD

**Issue by jc3213** [mozilla-jetpack/jpm#485]
Is there any chance that I can use &abc; in package.json to set abc as a l10n key in the locale.properties, as I used to do in options.xul before?It will be very helpful if there are options that uses the same l10n value.

Currently pref-name_options."value in the option label"=translation string in the locale.properties is too long. and if more than one options in different pref-name has the same string.it will cause lots of bytes to fulfill the l10n request as I only use 2 line when it is in options.xul

PS:I don't speak English as my native. Sorry if I haven't explained myself well. Maybe https://bugzilla.mozilla.org/show_bug.cgi?id=1210758 has better explanation than I reported here

**Comment by kumar303** [comment]
I think https://github.com/mozilla-jetpack/jpm/issues/479 should solve this for you, once it's implemented.

**Comment by jc3213** [comment]
@johannhof said I'd better create an new issue.If #479 could fix this, it will be welcomed

**Comment by kumar303** [comment]
ok, if it's better as a new issue then it would help to have a more concise feature request. If you can provide an example of a package.json file (formatted in the way you want) and the resulting locale properties file that should be created then this would be helpful.

**Comment by jc3213** [comment]
OK, Let's just use the sample in https://bugzilla.mozilla.org/show_bug.cgi?id=1210758 
  "preferences": [
    {
      "name": "test1",
      "type": "radio",
      "title": "test1",
      "value": true,
      "options": [
        {
          "value": true,
          "label": "&Enabled;"
        },
        {
          "value": false,
          "label": "&Disabled；"
        }
      ]
    },
    {
      "name": "test2",
      "type": "radio",
      "title": "test2",
      "value": true,
      "options": [
        {
          "value": true,
          "label": "&Enabled;"
        },
        {
          "value": false,
          "label": "&Disabled；"
        }
      ]
    }
  }


In locale.properties, I could only use

options.Enabled= 有効
options.Disabled= 無効


This is a very simple example. you can imagine that if both the preference title and the option label is more than 12 characters. and the preference which have the same l10n key is more than 3. It cost too much bytes and looks very ugly

**Comment by johannhof** [comment]
@kumar303 #479 is only about localizing name and description, and I'd like to not mix these two things, which would lead to more complex patches and complicated discussions.

**Comment by kumar303** [comment]
> if label Player could be changed into... &Override Flash Player (this is the way options.xul do), then options.Override Flash Player = プレイヤーをすり替える in the ja.properties will work for all the others

Thank you for this detailed explanation. I understand the feature request better now. I think this feature is not possible to add to jpm because we cannot change the `install.rdf` or locale properties format.

**Comment by jc3213** [comment]
Thanks for your answer, It will be OK though. Once I fired the bug on bugzilla cause  it is a feature request to the Add-ons SDK, but there seems to be no one who works on this.

**Comment by kumar303** [comment]
That is correct, all future features will be added to [Web Extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) because they will be cross platform.
