### ISSUE TITLE
jpm sign: better error when running from a non-SDK source directory

### ISSUE THREAD

**Issue by kumar303** [mozilla-jetpack/jpm#491]
Steps to reproduce:
* create a non-SDK add-on (anything with an install.rdf and bootstrap.js)
* cd into the directory
* run `jpm sign`

This usage is incorrect because jpm doesn't know how to build these types of add-ons. Instead the user should build an `xpi` file and run `jpm sign --xpi ...`. 

Instead, the user sees `Duplicate add-on ID found. ( status: 400 )` or `Version does not match install.rdf` which is pretty confusing. Attached is a directory of source code that reproduces it.
[jpm-non-sdk-bug.zip](https://github.com/mozilla-jetpack/jpm/files/125569/jpm-non-sdk-bug.zip)

We can provide a better error

**Comment by jc3213** [comment]
If you run `jpm xpi` first, you will get `null.xpi` that approves jpm can't parse information from non-SDK add-ons(yet, from an `install.rdf`). I think if jpm could parse information first from package.json, if no then install.rdf, at last it can pack non-SDK add-ons then sign it without problem.

**Comment by kumar303** [comment]
Now it looks like:
````
JPM [error] FAIL
Error: Could not detect this XPI's ID and/or version

Troubleshooting:
- Are you in the right directory? If not, try --addon-dir
- Are you really in a directory of SDK add-on source? If not, try signing with the --xpi option
````
