### ISSUE TITLE
why the info logs are not printed when NODE_ENV=test ?

### ISSUE THREAD

**Issue by arieljannai** [mozilla-jetpack/jpm#492]
Hello there,

In [utils.js L73](https://github.com/mozilla-jetpack/jpm/blob/master/lib/utils.js#L73) there's this piece of code:
``` 
if (process.env.NODE_ENV !== "test") {
    console.log.apply(console, [first].concat(messages));
}
```

Why is it necessary? why not all the info is printed in `test` mode?
Is it because it interrupt your tests?

Thanks

**Comment by kumar303** [comment]
I think this decision was made so that the test suite did not spew a lot of text on the screen.
