### ISSUE TITLE
Publish PsuedoProgress as a separate module

### ISSUE THREAD

**Issue by meandavejustice** [mozilla-jetpack/jpm#496]
I just tried out `jpm sign` for the first time(it works great!) and really liked the [progress animation](https://github.com/mozilla-jetpack/jpm/blob/6a387ef466f9f80fb8a3666ae0845a9544c76390/lib/amo-client.js#L507). Would love to be able to use this is another project without copy & pasting

**Comment by kumar303** [comment]
Hmm, at this time I'm not keen on maintaining a separate package. I would recommend just copying and pasting it for now. It will probably be easier for you. However, if you want to make a separate package and patch jpm to depend on it, I will consider the patch.
