### ISSUE TITLE
addon version is created with preliminary review even when the clock is drifted

### ISSUE THREAD

**Issue by Marcelovk** [mozilla-jetpack/jpm#511]
Steps to reproduce:

1-) Change your clock 1 minutes backward
2-) Try signing an addon via jpm sign: It should give an error 401 and a message telling to use TLSdate
3-) Fix your clock (Via tlsdate, ntpdate) and try again. This time the message is 409 - Version already exists. Updating package.json and trying again works.

Am I right that the version should not be created in those cases ? Tested with jpm 1.0.6

**Comment by kumar303** [comment]
> Am I right that the version should not be created in those cases ? Tested with jpm 1.0.6

This is correct. Does it happen every time you try it?

**Comment by Marcelovk** [comment]
No, it does not happen every time, I could not reproduce it consistently. I tried just now, and it worked correctly

**Comment by kumar303** [comment]
I think that there must be another explanation for how the version was created (triggering a duplicate error on the next attempt). I am confident that we have adequate protection in our view handlers that a 401 response would not somehow create a new version. If it happens again, let us know.
