### ISSUE TITLE
Make jpm sign use the sign-addon module

### ISSUE THREAD

**Issue by kumar303** [mozilla-jetpack/jpm#519]
Now that [sign-addon](https://github.com/mozilla/sign-addon/) has been published, convert jpm to using it. The code was actually extracted from jpm so it should be straight forward.

**Comment by yan12125** [comment]
@kumar303 Have you started a WIP?

**Comment by kumar303** [comment]
@yan12125 I haven't started, no. We just published a new [sign-addon](https://www.npmjs.com/package/sign-addon); it's stable and ready to go. If you want to work on switching jpm over to it, please do. I can help review and test.

**Comment by yan12125** [comment]
A question: sign-addon uses ES6 everywhere. Does that mean old node.js versions are no longer supported?

**Comment by kumar303** [comment]
No, it only uses ES6 in the source. It is distributed as ES5 code. You can use it in jpm just like any other ES5 module. The README has an example: https://github.com/mozilla/sign-addon/#programmatic-use

**Comment by yan12125** [comment]
Thanks for that. Here's a work-in-progress patch:
```Diff
diff --git a/lib/sign.js b/lib/sign.js
index 37d0ed5..88f6033 100644
--- a/lib/sign.js
+++ b/lib/sign.js
@@ -8,6 +8,7 @@ var tmp = require("tmp");
 var nodefn = require("when/node");
 var path = require("path");
 var when = require("when");
+var signAddon = require('sign-addon').default;
 
 var DefaultAMOClient = require("./amo-client").Client;
 var cmd = require("./cmd");
@@ -109,20 +110,19 @@ function sign(options, config) {
              "signing with the --xpi option\n");
     }
 
-    var client = new config.AMOClient({
+    return signAddon({
+      xpiPath: xpiInfo.xpiPath,
+      id: xpiInfo.id,
+      version: xpiInfo.version,
       apiKey: options.apiKey,
       apiSecret: options.apiSecret,
       apiUrlPrefix: options.apiUrlPrefix,
-      debugLogging: options.verbose,
-      signedStatusCheckTimeout: options.timeout || undefined,
-    });
-    return client.sign({
-      xpiPath: xpiInfo.xpiPath,
-      guid: xpiInfo.id,
-      version: xpiInfo.version,
+      verbose: options.verbose,
+      timeout: options.timeout || undefined,
+      AMOClient: config.AMOClient,
     }).then(function(result) {
       if (typeof xpiInfo.cleanUp !== "undefined") {
-        client.debug("cleaning up XPI temp directory");
+        logger.debug("cleaning up XPI temp directory");
         xpiInfo.cleanUp();
       }
       return result;
diff --git a/package.json b/package.json
index 26b6f1b..ba042d9 100644
--- a/package.json
+++ b/package.json
@@ -55,6 +55,7 @@
     "read": "1.0.7",
     "request": "2.67.0",
     "semver": "5.1.0",
+    "sign-addon": "0.1.0",
     "tmp": "0.0.28",
     "when": "3.7.2",
     "xml2js": "0.4.16",
```
2 tests in ```npm test unit``` fail, as they use a fake XPI path while ```sign-addon``` enforces strict path checks. Seems I need to modify sign-addon for these tests? Unfortunately I don't know how to generate an ES5 ```dist/sign-addon.js``` from ES6 sources. Tried this command in the root folder of ```sign-addon```:
```
npm run build
```
However, the generated file still contains ES6 syntaxes.
Sorry if the last question sounds stupid :(

**Comment by kumar303** [comment]
Hi, thanks for getting this started. Here are some notes:
* this would be a good time to open a pull request to make it easier to review
* part of the patch should be removing all the existing signing and amo-client code since it won't be needed anymore
* I think most unit tests can use a stub version of `signAddon()`

**Comment by kumar303** [comment]
> I think most unit tests can use a stub version of `signAddon()`

This is a change you'd need to make to the current test suite. The current test suite does not always stub out the `signAddon()` function because it needs to cover some of its internal functionality. Now that `signAddon()` is a third party lib, jpm's test suite no longer needs to cover its internal functionality. We can simply rely on it as an interface.

**Comment by yan12125** [comment]
> this would be a good time to open a pull request to make it easier to review

Here it is :) #546
