### ISSUE TITLE
Add an option to not fail if signing an add-on that is expected to be reviewed

### ISSUE THREAD

**Issue by Standard8** [mozilla-jetpack/jpm#520]
We're currently writing automation to upload an xpi to the developer channel on AMO regularly.

Currently the script "fails" because of the fact the add-on normally gets submitted for review. However, as we know we this is the case, it'd be nice if we could add some sort of option to ignore the review warning failure, and act as if it uploaded fine.

**Comment by kumar303** [comment]
The need for review is a legitimate signing failure so I'd rather not add a way to ignore it. It sounds like you would be better off by creating a wrapper script that accessed jpm directly. You could do so in Node like:
````
var signCmd = require('jpm/lib/sign').signCmd;
signCmd({apiKey: ...})
  .then(function(result) {
    console.log(result);
  })
  .catch(function(error) {
    console.log(error);
  });
````
Thanks for taking the time to file an issue but it doesn't sound like the right kind of feature for the command line.

PS. you can also use [sign-addon](https://github.com/mozilla/sign-addon/) directly now.
