### ISSUE TITLE
Lodash`s version should be update

### ISSUE THREAD

**Issue by muhawo** [mozilla-jetpack/jpm#524]
>npm WARN unmet dependency .\node_modules\grunt-jpm\node_modules\jpm requires lodash@'3.10.1' but will load
npm WARN unmet dependency .\node_modules\lodash,
npm WARN unmet dependency which is version 4.11.1

some other modules will upgrage lodash autoly, and then the problem above is showed.
>npm WARN deprecated lodash@2.1.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

**Comment by johannhof** [comment]
Closed by #525

**Comment by freaktechnik** [comment]
To make sure none of the dependencies maintained here are using an old lodash, https://github.com/mozilla-jetpack/node-fx-runner/blob/master/package.json#L30 should probably be updated too.
