### ISSUE TITLE
support code coverage in tests

### ISSUE THREAD

**Issue by gregglind** [mozilla-jetpack/jpm#528]
Revisiting this issue after a long rest, during which lots of tools got better :)

Current State
1.  gotwarlost/istanbul `cover` works fine.  `test` does not.  ES6 / fx is well supported now.
2.  there is no current easy to hook globals in xpi addons (is there?)
3.  `jpm test` isn't a direct node command so it's kind of out-of-phase with how istanbul expects to do things.

Stuff that might work:
1.  pre-running `instanbul cover` then testing on that (using some sort pre-hook)
2.  Even then, there is no 'globals/window/this' in that enviroment.  Ideas welcome.  In the old require system, you could do this with pseudo modules.  Might be nice if every module had `__cover__` reserved for that use.

I don't know how much this is jpm's problem vs. the sdk.

**Comment by freaktechnik** [comment]
I've already solved that problem: https://www.npmjs.com/package/istanbul-jpm

**Comment by gregglind** [comment]
Wow, that is awesome!  Glad to publicize it!

**Comment by freaktechnik** [comment]
I thought I had mentioned that in the README, but example usage can be seen on https://github.com/freaktechnik/justintv-stream-notifications.
