### ISSUE TITLE
Node warning: please update graceful-fs module to a more recent version.

### ISSUE THREAD

**Issue by jc3213** [mozilla-jetpack/jpm#531]
node.exe 6.2.0 (x64) running `jpm -V`, The command-line console alerts `(node:7244) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.` then display `1.0.7`

**Comment by kumar303** [comment]
it's in one of our dependencies. We just need to track it down and upgrade the dependency (if it has been fixed).

**Comment by freaktechnik** [comment]
I think npm install actually says where the deprecated graceful-fs version is coming from.

**Comment by jc3213** [comment]
I was using jpm xpi to package xpi files and the console warns about it `(node:34596) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.`

And when using npm install jpm, many module has been alterted that is deprecated and I can hardly remember one of them alerts that the old version will not be compatible with nodejs 7.0.0

**Comment by Croydon** [comment]
`npm ls graceful-fs -g` does the magic.

[fs-extra](https://www.npmjs.com/package/fs-extra) needs to get updated (directly in this repo).
