### ISSUE TITLE
"Both install_rdf and manifest.json found" and "Unable to determine add-on type"

### ISSUE THREAD

**Issue by JohnPaulHarold** [mozilla-jetpack/jpm#539]
I'm getting General error such as in the title.

> **Both install_rdf and manifest.json found**
> _Error: The type should be determined by manifest.json if present. Both install_rdf and manifest_json are defined._
> **Unable to determine add-on type**
> _Error: The type detection algorithm could not determine the type of the add-on._
> 

But it's unclear what I'm supposed to do to remedy them. How do I declare what the 'type' of the extension is, and where? This is an extension that I can load unpacked via `about:debugging` and now I'd like to sign and compile to an `xpi` so I can distribute privately around the workplace. It's derived from a Chrome extension.

I'm doing a very basic `jpm sign` with my key and secret, inside the extension folder (where the manifest and package are). I've got a log of the output I can post somewhere preferred.

**Comment by andymckay** [comment]
Do you have both install.rdf and manifest.json? The latter file is only used by WebExtensions, so AMO is unclear if your add-on is a jpm style SDK add-on or a WebExtension addon, it can't be both.

**Comment by JohnPaulHarold** [comment]
I'm not personally creating, editing or anything with an install.rdf. If I create an xpi via `jpm xpi` inside the extension folder, and then 

```
zipinfo -1 myxpi.xpi | grep "install.rdf"
install.rdf
```

There it is. How can I then build an xpi without this `install.rdf`? Is there a special flag for this?

**Comment by andymckay** [comment]
`jpm xpi` creates the `install.rdf` and tells AMO that its in an SDK add-on. So what is the `manifest.json` in your add-on for?

**Comment by JohnPaulHarold** [comment]
the manifest.json is there because the add on is a WebExtension. I'm working through this https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Packaging_and_installation

**Comment by andymckay** [comment]
If its a WebExtension, please use `web-ext` since `jpm` is only for SDK addon's. Its like `jpm` but supports WebExtensions. I didn't see any reference on that page to `jpm` so not sure how you get there.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext

**Comment by JohnPaulHarold** [comment]
That's great! I think my confusion was following links here
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Packaging_and_installation#Getting_your_add-on_signed

Which to me, leads straight onto `jpm` docs. In fact, I don't see how to get to the page you've linked to from the docs.

Anyway, thanks for the help.

**Comment by andymckay** [comment]
Ah I see why you ended up there, I improved: https://developer.mozilla.org/en-US/Add-ons/Distribution#Signing_API a little to explain the difference.

Thanks
