### ISSUE TITLE
Fail if there's a manifest.json

### ISSUE THREAD

**Issue by andymckay** [mozilla-jetpack/jpm#540]
If the package has a `manifest.json` in the root (it's a WebExtension) then we should probably just fail and raise a nice error message saying "please go use web-ext". This will help people who hit issues like #539

**Comment by rpl** [comment]
This issue seems to be possible only if the add-on directory contains both a `manifest.json` and a `package.json` file (which can be the case if a WebExtension is built from a directory which is also an npm package).

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla-jetpack/jpm/pull/541
