### ISSUE TITLE
Set XPI output directory?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-jetpack/jpm#556]
I haven't seen a way to do this, but maybe I'm missing something obvious in the docs/API.

In a bunch of our projects, we have a general flow like this where we run `jpm xpi` and then move/rename the generated XPI into a new folder. Is there a way to specify an output directory/filename when calling `jpm xpi` so we don't have to do this as a separate step?

```js
"package": "npm run build-script && jpm xpi && mv min-vid.xpi dist/addon.xpi",
```

(Where we run `$ npm run package` and it runs our `build-script` task, then calls `jpm xpi` and finally moves and renames the generated ./min-vid.xpi to the ./dist/addon.xpi directory.)

**Comment by freaktechnik** [comment]
See #544

**Comment by kumar303** [comment]
Thanks for the report @pdehaan. We are tracking this in https://github.com/mozilla-jetpack/jpm/issues/315
