### ISSUE TITLE
package.json incompatibility between cfx and jpm

### ISSUE THREAD

**Issue by kharts15** [mozilla-jetpack/jpm#559]
While converting my cfx based build to jpm I ran into the following problem:

I need my add-on to be unpacked, so I have the following in my package.json
  "unpack": "true"

This ends up as false in the install.rdf  
This was not the case when using cfx

To resolve the issue I modified my package.json entry to
"unpack": true

Just a heads up in case this can be made backwards compatible.

**Comment by Croydon** [comment]
"true" is a string instead of a boolean, so I guess it's more a question of how liberal vs. strict it should be..
The value as a string is not really correct, so imho it's not an issue.

**Comment by kumar303** [comment]
That field in `package.json` must be a boolean, yes. It would be non-trivial to add validation for something like this since we'd have to create a schema defining the types of each field in `package.json`. Because of the complexity involved, I'm closing the issue. Thanks for the report though.
