### ISSUE TITLE
Fix travis builds not being able to install unsigned extensions

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-jetpack/jpm#562]
There are four solutions to this:

 - Use the latest ESR (I think this will work until the next major ESR version)
 - Specify that we want to test against Firefox 47.0
 - Use a tool to download an unbranded build or dev-edition/nightly (dev-edition and nightly are easier afaik)
 - Fix #468 

Thanks @asamuzaK for pointing the build failures of the merge of #561 out.

**Comment by kumar303** [comment]
Hmm, I don't see [explicit support](https://docs.travis-ci.com/user/firefox/) from TravisCI for nightly or dev-edition. ESR gets updated infrequently so it may not be a good candidate.

We used to have code that [manually downloaded and installed a firefox binary](https://github.com/mozilla-jetpack/jpm/blob/master/.travis.yml#L9-L13) so it shouldn't be too hard to resurrect that and point it at an [unbranded build](https://wiki.mozilla.org/Addons/Extension_Signing#Unbranded_Builds).

**Comment by k88hudson** [comment]
Hey there, we noticed this yesterday on `mozilla/activity-stream`. For now we've decided to target nightly for local dev and stick to an earlier release of Firefox for CI, but I've been looking into other possible solutions.

Any possibility `jpm run/test` could be updated to use the `installTemporaryAddon` strategy in `about:debugging`? Not sure how much if it would work/is feasible,  just wondering

**Comment by kumar303** [comment]
hi @k88hudson, I offered my idea for how to make jpm use the `installTemporaryAddon` strategy here: https://github.com/mozilla-jetpack/jpm/issues/468#issuecomment-237074698 I think it's just a matter of extracting the web-ext code into a new lib and shaving some yaks.

Also, to avoid confusion, the issue in this thread is about jpm's internal test suite, not the `jpm test` command.

**Comment by k88hudson** [comment]
@kumar303 ok, thanks!

**Comment by kumar303** [comment]
I switched to using Nightly in CI (https://github.com/mozilla-jetpack/jpm/pull/568) but I think it would be nicer to use an unbranded release build. The release build will be more stable and is a more likely candidate for what jpm developers will use. 

@freaktechnik did you want to try using your get-firefox script to get unbranded builds? I will leave this issue open if that's the case.

**Comment by freaktechnik** [comment]
I use get-firefox in my personal travis runs, so it shouldn't be too hard.
