### ISSUE TITLE
Stops on `JPM [info] Creating a new profile`

### ISSUE THREAD

**Issue by anton-aleksandrov** [mozilla-jetpack/jpm#563]
I was developing Firefox Add on. I needed to switch language in Firefox browser. If i get it correctly, then the only way to do that is to reinstall entire browser. So, i did it, and now, when i'm trying to run Add on, i'm getting this:

    JPM [info] Starting jpm run on AddonName addon
    JPM [warning] Using existing install.rdf. This file is usually auto-generated.
    JPM [info] Creating a new profile

... and that's all, nothing else happen: no errors, no messages - just this.  
Well, it does open browser, but the add on is not there. Before firefox reinstallation, it was working absolutely fine.  
What's wrong with this sdk?

I use OS X El Captain latest

I've tried to:   
 - reinstall firefox again,  
 - delete `install.rdf`,  
 - reinstall `jpm`,  
 - Run `/Applications/Firefox.app/Contents/MacOS/firefox-bin -P`, create new profile and use it. Terminal output is different, but add on still not showing up in browser.

Neither makes any difference.

**Comment by freaktechnik** [comment]
This is with a release Firefox?

**Comment by anton-aleksandrov** [comment]
Not sure - atm i can't make sure, if i had the same version of firefox as i do now

**Comment by freaktechnik** [comment]
I'm asking because on regular stable and beta jpm doesn't work at the moment, you have to use unbranded builds there, or use dev edition or nightly for development.

**Comment by anton-aleksandrov** [comment]
Thank you, it helped: i've installed ff dev edition

**Comment by kumar303** [comment]
@anton-aleksandrov you could also use an unbranded release build if needed https://wiki.mozilla.org/Addons/Extension_Signing#Unbranded_Builds
