### ISSUE TITLE
jpm sign support for proxy

### ISSUE THREAD

**Issue by vidyavijayabhanu** [mozilla-jetpack/jpm#582]
Hi
We have a requirement where jpm sign command need to be run through a proxy.
We dont want all computers to have internet connection to run jpm sign command.
Hence we need to run jpm sign command through a proxy and submit addon for Mozilla signing.
Does jpm sign command currently supports running it through proxy?

**Comment by yan12125** [comment]
It's not implemented yet. See #446

**Comment by kumar303** [comment]
Hi. yes, it is tracked in https://github.com/mozilla-jetpack/jpm/issues/446 . If someone has bandwidth to work on this feature, I can mentor the patch. It is pretty straight forward.
