### ISSUE TITLE
npm upgrade `request` to stop 'tough-cookie' warning

### ISSUE THREAD

**Issue by gregglind** [mozilla-jetpack/jpm#583]
```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

Current versions of `request` don't have this issue.

https://nodesecurity.io/advisories/130

**Comment by freaktechnik** [comment]
See #580

**Comment by kumar303** [comment]
thanks @freaktechnik , I was just hunting for that. 

@gregglind thanks for the report, we're tracking it in #580. However, note that set-cookie vulnerabilities probably don't apply to `jpm` since it has no website component.

**Comment by gregglind** [comment]
Mostly it causes annoying WARN for other things that install jpm :) 

Thanks for already having it solved!
