### ISSUE TITLE
Odd Array/String coercion in lib/rdf.js

### ISSUE THREAD

**Issue by pdehaan** [mozilla-jetpack/jpm#584]
Ref: [lib/rdf.js:250](https://github.com/mozilla-jetpack/jpm/blob/5f7a5acdd3d166181392b7657bf968dc52fe0f63/lib/rdf.js#L250),

```js
// TODO: Figure out why this fails w/ `===`
if (Object.keys(descriptionData) == "em:targetApplication") { // eslint-disable-line eqeqeq
```

This feels very dirty to me. [`Object.keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) returns an ~~object~~ Array, but we're trying to compare it to a string (which works with `==` but not with strict `===`).

```js
const foo = ['bin'];
const bar = 'bin';

console.log(foo == bar); // true
console.log(foo === bar); // false
```

I had to add an `// eslint-disable-line eqeqeq` and live with my never ending abyss of ESLint shame.

**Comment by kumar303** [comment]
Huh, looks like this was a bug. Who knows. The jpm legacy is rife with obscure javascript tricks like `return ~DEBUG_VALUES.indexOf(option)` 🚑 

I think this line can definitely be changed. However, I have always been a little hesitant to change little things like this because the test coverage isn't great. Don't let that stop you though! We have a passionate user base who are great about filing bugs after new releases.

**Comment by kumar303** [comment]
> ... because the test coverage isn't great

And the functional test suite is especially cumbersome to deal with

**Comment by pdehaan** [comment]
Off the top of your head, do you know what the fix is?
```js
if (Object.keys(descriptionData).indexOf("em:targetApplication") !== -1) {...}
```

I'm kind of amazed that the code ever worked (and an Array could be coerced into a string, so I'm mentally trying to wrap my head around what the coercion logic is.

**Comment by freaktechnik** [comment]
I think it works only for one element arrays, so you should be able to just compare the first element, or even better use the `in` operator or `hasOwnProperty` directly on `descriptionData`.

**Comment by pdehaan** [comment]
Submitted #588

Spoiler alert:

```js
if (descriptionData.hasOwnProperty("em:targetApplication")) {...}
```
