### ISSUE TITLE
Will build with AOM support if min version is bigger than 50.0a

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-jetpack/jpm#590]
AOM support, which is install.rdf free SDK extensions never happened, but the code still thinks it will be in for Firefox 50.0a, which is defined in https://github.com/mozilla-jetpack/jpm/blob/master/lib/settings.js#L13. I think the easiest fix is to remove https://github.com/mozilla-jetpack/jpm/blob/master/lib/utils.js#L27 and use false as replacement wherever it is used.

**Comment by kumar303** [comment]
Oh, huh. I don't know much about it. I suppose weird things will happen in Firefox 50 if we don't remove it? I'm all for removing things from jpm.

**Comment by freaktechnik** [comment]
If someone sets the minversion for something bigger or equal to 50.0a (which will be quite common for embedded WebExtensions I imagine) JPM will not include install.rdf and bootstrap.js since it believes that Firefox version natively supports loading SDK extensions.
