### ISSUE TITLE
Set multiprocessCompatible flag for package.json multiprocess permission regardless of value

### ISSUE THREAD

**Issue by jxpx777** [mozilla-jetpack/jpm#607]
Per [The Road to Firefox 57](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/), extensions that are not e10s compatible must explicitly set the multiprocessCompatible flag to false in install.rdf. For some add-ons such as 1Password, the add-on SDK is never going to be fully e10s compatible for all the APIs that are in use so setting this flag to an explicitly false value will be required.

Setting package.json's multiprocess permission to true causes the `<em:multiprocessCompatible>true</em:multiprocessCompatible>` tag to be added, but setting it to false, causes the tag to be omitted. This is clear from the code at [rdf.js:105](https://github.com/mozilla-jetpack/jpm/blob/4561d481885f732bf30fcc77044583fe6fe028fd/lib/rdf.js#L105). Without an else branch here, the extension must create its own complete install.rdf _and_ ensure it is updated in the xpi during build. Instead, jpm should respect the presence and value of the multiprocess permission in package.json regardless of its value.

**Comment by kumar303** [comment]
Whoops, good catch. Thanks for the bug report.

I can review a patch but I'm not sure who would have time to work on it.

As a workaround you can manually edit the auto-generated rdf code in your extension, I think?

As an aside, I would recommend that you check out which [WebExtension APIs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) are missing for 1Password and be sure bugs are on file to [add those APIs](https://webextensions-experiments.readthedocs.io/en/latest/why.html). Moving 1Password to a WebExtension is the most ideal fix.

**Comment by kumar303** [comment]
> As an aside, I would recommend that you check out which WebExtension APIs...

Oh, hey, I just remembered that there is a Chrome version of 1Password. Firefox pretty much supports the same extension API as Chrome. Have you tried [running the Chrome version in Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension)?

**Comment by jxpx777** [comment]
Moving to WebExtensions is indeed our plan but there are a couple things blocking us (Bug [1257989](https://bugzilla.mozilla.org/show_bug.cgi?id=1257989) means we must use only Native Messaging, which requires platform apps to all be up to date and we have legacy users of our extension back to 1Password 4 on Mac and Windows that will not get updated for native messaging, so we need to leave a legacy version for them going forward. I know Firefox 57 will remove SDK add-on support entirely but until then we need to make sure we have compatibility going from 53 to 57.)

I'll try to get a patch ready for this issue today. Seems it's probably pretty straightforward.

**Comment by kumar303** [comment]
Yeah, a patch should be straight forward. I'd suggest only running `npm run unit` -- don't worry about the functional suite (it's annoying). You probably only need to touch https://github.com/mozilla-jetpack/jpm/blob/master/test/unit/test.rdf.js

**Comment by jxpx777** [comment]
@kumar303 I made the patch. Pretty straightforward like you said. Let me know if there's anything else to do to move it forward.

**Comment by kumar303** [comment]
Thanks, I requested a review from myself so I won't forget to look at it next week. There is one eslint failure because of line length which needs fixing. There is a `changelog-lint` error because of the [commit message](https://github.com/mozilla-jetpack/jpm/blob/master/CONTRIBUTING.md#writing-commit-messages) but you can ignore that one -- it's a pain to fix unless you like rebasing.

**Comment by jxpx777** [comment]
@kumar303 Can you let me know what the issue is with line length? My changes have a max line length of 77 characters… (81 characters if you count whitespace)

**Comment by freaktechnik** [comment]
The eslint google preset expects 80 characters excluding linebreak. The eslint error happens on line 106 of rdf.js (https://travis-ci.org/mozilla-jetpack/jpm/jobs/214746833#L1029). So the line is exactly one character too long.

**Comment by jxpx777** [comment]
I pushed a change to conform. I like the code less, but _c'est la vie_.

**Comment by kumar303** [comment]
Thanks again @jxpx777 , I'll cut a new release for this shortly.

**Comment by kumar303** [comment]
I just released it in 1.3.1. The package may take a bit to appear on NPM. https://github.com/mozilla-jetpack/jpm/releases/tag/1.3.1
